### ISSUE TITLE
Console spammed with "REDIRECT"

### ISSUE THREAD

**Issue by srnyx** [Flytre/flytre-gun-mod#1]
The latest version spams my console with REDIRECT (literally just REDIRECT)

**Comment by Flytre** [comment]
Screenshot would be appreciated, as well as what you were doing when that happened.

**Comment by srnyx** [comment]
> Screenshot would be appreciated, as well as what you were doing when that happened.

Ok, it may not be your mod. I thought it stopped but now it's doing it again:
![image](https://user-images.githubusercontent.com/25808801/109075755-9a0c5100-76c7-11eb-83dd-6cbe53c9c49b.png)
_I downgraded to make it stop_


Going to see if my server host has anything to do with it as "REDIRECT" isn't coming in latest.log
